Server:
  RunMode: debug
  HTTPPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
Log:
  LogSavePath: storage/logs
  LogFileName: app.log
  Level: debug
  MaxSize: 10
  MaxBackups: 5
  Compress: False
Database:
  DBType: mysql
  Username: root
  Password: helloworld
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  MigrationURL: "file://db/migration"
Ratelimit:
  Enable: true
  ConfigFile: sentinel.yml
  CPULoadThresh: 0
  CPULoadStrategy: -1 # 0: BBR, -1: NoAdaptive
